import { createContext, useContext, useState, useEffect } from "react";

const ProductContext = createContext();

export const useProducts = () => {
  const context = useContext(ProductContext);
  if (!context)
    throw new Error("useProducts must be used within ProductProvider");
  return context;
};

// Default products from NCC catalog
const defaultProducts = [
  // 600x600 Glossy
  {
    id: 1,
    code: "MSG66002M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["White", "Beige", "Grey", "Black"],
    price: 45.99,
    inStock: true,
    image: null,
  },
  {
    id: 2,
    code: "MSG66003M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Cream", "Ivory", "Brown"],
    price: 47.99,
    inStock: true,
    image: null,
  },
  {
    id: 3,
    code: "MSG66004M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Pearl", "Sand", "Charcoal"],
    price: 46.99,
    inStock: true,
    image: null,
  },
  {
    id: 4,
    code: "MSG66005S",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Marble White", "Marble Grey"],
    price: 49.99,
    inStock: true,
    image: null,
  },
  {
    id: 5,
    code: "MSG66006M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Light Grey", "Dark Grey"],
    price: 48.99,
    inStock: true,
    image: null,
  },
  {
    id: 6,
    code: "MSG66007M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Vanilla", "Champagne"],
    price: 47.99,
    inStock: true,
    image: null,
  },
  {
    id: 7,
    code: "MSG66008M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Snow White", "Pearl Grey"],
    price: 46.99,
    inStock: true,
    image: null,
  },
  {
    id: 8,
    code: "MSG66009M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Ivory Cream", "Stone Grey"],
    price: 48.99,
    inStock: true,
    image: null,
  },
  {
    id: 9,
    code: "MSG66010M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Pure White", "Graphite"],
    price: 49.99,
    inStock: true,
    image: null,
  },
  {
    id: 10,
    code: "MSG66011M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Bone White", "Slate Grey"],
    price: 47.99,
    inStock: true,
    image: null,
  },
  {
    id: 11,
    code: "MSG66012M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Arctic White", "Charcoal"],
    price: 48.99,
    inStock: true,
    image: null,
  },
  {
    id: 12,
    code: "MSG66013M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Cream Beige", "Ash Grey"],
    price: 46.99,
    inStock: true,
    image: null,
  },
  {
    id: 13,
    code: "MSG66014M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Natural White", "Steel Grey"],
    price: 47.99,
    inStock: true,
    image: null,
  },
  {
    id: 14,
    code: "MSG66015M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Silk White", "Titanium"],
    price: 49.99,
    inStock: true,
    image: null,
  },
  {
    id: 15,
    code: "MSG66016M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Porcelain White", "Onyx"],
    price: 48.99,
    inStock: true,
    image: null,
  },
  {
    id: 16,
    code: "MSG66017M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Crystal White", "Midnight"],
    price: 47.99,
    inStock: true,
    image: null,
  },
  {
    id: 17,
    code: "MSG66022M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Bright White", "Carbon"],
    price: 46.99,
    inStock: true,
    image: null,
  },
  {
    id: 18,
    code: "MSG66023M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Linen", "Pepper"],
    price: 48.99,
    inStock: true,
    image: null,
  },
  {
    id: 19,
    code: "MSG66024M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Alabaster", "Jet Black"],
    price: 49.99,
    inStock: true,
    image: null,
  },
  {
    id: 20,
    code: "MSG66025M",
    name: "Glossy Porcelain Tile",
    category: "600x600 Glossy",
    sizes: ["600x600"],
    colors: ["Cotton", "Ebony"],
    price: 47.99,
    inStock: true,
    image: null,
  },

  // 600x600 Polished
  {
    id: 21,
    code: "NRP660016",
    name: "Polished Porcelain Tile",
    category: "600x600 Polished",
    sizes: ["600x600"],
    colors: ["Marble White", "Marble Grey", "Marble Black"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 22,
    code: "NRP660024",
    name: "Polished Porcelain Tile",
    category: "600x600 Polished",
    sizes: ["600x600"],
    colors: ["Ivory Polish", "Grey Polish"],
    price: 54.99,
    inStock: true,
    image: null,
  },
  {
    id: 23,
    code: "NRP660038",
    name: "Glazed Porcelain Tile",
    category: "600x600 Glazed",
    sizes: ["600x600"],
    colors: ["Glossy White", "Glossy Grey"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 24,
    code: "NRP660046",
    name: "Glazed Porcelain Tile",
    category: "600x600 Glazed",
    sizes: ["600x600"],
    colors: ["Shine Beige", "Shine Brown"],
    price: 53.99,
    inStock: true,
    image: null,
  },
  {
    id: 25,
    code: "NRP660151",
    name: "Polished Porcelain Tile",
    category: "600x600 Polished",
    sizes: ["600x600"],
    colors: ["Premium White", "Premium Grey"],
    price: 55.99,
    inStock: true,
    image: null,
  },
  {
    id: 26,
    code: "NRP660161",
    name: "Polished Porcelain Tile",
    category: "600x600 Polished",
    sizes: ["600x600"],
    colors: ["Luxury Cream", "Luxury Grey"],
    price: 56.99,
    inStock: true,
    image: null,
  },
  {
    id: 27,
    code: "NRP660176",
    name: "Polished Porcelain Tile",
    category: "600x600 Polished",
    sizes: ["600x600"],
    colors: ["Elite White", "Elite Black"],
    price: 54.99,
    inStock: true,
    image: null,
  },
  {
    id: 28,
    code: "NRP660186",
    name: "Polished Porcelain Tile",
    category: "600x600 Polished",
    sizes: ["600x600"],
    colors: ["Select Ivory", "Select Charcoal"],
    price: 55.99,
    inStock: true,
    image: null,
  },

  // 600x600 Matt (Slip Resistant)
  {
    id: 29,
    code: "MSM66031M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Matte White", "Matte Grey", "Matte Beige"],
    price: 42.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 30,
    code: "MSM66032M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Stone Grey", "Earth Brown"],
    price: 43.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 31,
    code: "MSM66033M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Sand Beige", "Clay Brown"],
    price: 44.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 32,
    code: "MSM66034M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Natural Grey", "Rust Brown"],
    price: 43.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 33,
    code: "MSM66010M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Frost White", "Frost Grey"],
    price: 42.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 34,
    code: "MSM66011M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Cloud White", "Storm Grey"],
    price: 44.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 35,
    code: "MSM66012M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Mist Grey", "Dusk Brown"],
    price: 43.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 36,
    code: "MSM66013M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Haze White", "Shadow Grey"],
    price: 42.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 37,
    code: "MSM66014M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Pearl White", "Slate Grey"],
    price: 44.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 38,
    code: "MSM66015M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Silk Beige", "Granite Grey"],
    price: 43.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 39,
    code: "MSM66016M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Linen White", "Basalt Grey"],
    price: 45.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },
  {
    id: 40,
    code: "MSM66017M",
    name: "Matt Porcelain Tile",
    category: "600x600 Matt",
    sizes: ["600x600"],
    colors: ["Canvas White", "Quarry Grey"],
    price: 44.99,
    inStock: true,
    slipResistant: true,
    image: null,
  },

  // 600x600 Porcelain (MSP Series)
  {
    id: 41,
    code: "MSP66001",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Classic White", "Classic Grey"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 42,
    code: "MSP66002M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Modern White", "Modern Grey"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 43,
    code: "MSP66003M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Contemporary Beige", "Contemporary Grey"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 44,
    code: "MSP66004M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Traditional Cream", "Traditional Brown"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 45,
    code: "MSP66009M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Heritage White", "Heritage Grey"],
    price: 53.99,
    inStock: true,
    image: null,
  },
  {
    id: 46,
    code: "MSP66010M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Signature White", "Signature Grey"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 47,
    code: "MSP66011M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Prestige Beige", "Prestige Grey"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 48,
    code: "MSP66012M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Advantage White", "Advantage Grey"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 49,
    code: "MSP66017M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Benefit White", "Benefit Grey"],
    price: 54.99,
    inStock: true,
    image: null,
  },
  {
    id: 50,
    code: "MSP66018M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Value Beige", "Value Brown"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 51,
    code: "MSP66019M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Prime White", "Prime Grey"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 52,
    code: "MSP66020M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Choice Cream", "Choice Charcoal"],
    price: 53.99,
    inStock: true,
    image: null,
  },
  {
    id: 53,
    code: "MSP66021M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Select White", "Select Black"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 54,
    code: "MSP66022M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Optimal Grey", "Optimal Beige"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 55,
    code: "MSP66023M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Ideal White", "Ideal Grey"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 56,
    code: "MSP66024M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Perfect Cream", "Perfect Brown"],
    price: 54.99,
    inStock: true,
    image: null,
  },
  {
    id: 57,
    code: "MSP66041M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Essential White", "Essential Grey"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 58,
    code: "MSP66042M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Fundamental Beige", "Fundamental Grey"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 59,
    code: "MSP66043M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Basic White", "Basic Charcoal"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 60,
    code: "MSP66044M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Standard Cream", "Standard Brown"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 61,
    code: "MSP66049M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Core White", "Core Grey"],
    price: 53.99,
    inStock: true,
    image: null,
  },
  {
    id: 62,
    code: "MSP66050M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Central Beige", "Central Grey"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 63,
    code: "MSP66051M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Main White", "Main Black"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 64,
    code: "MSP66052M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Primary Cream", "Primary Brown"],
    price: 54.99,
    inStock: true,
    image: null,
  },
  {
    id: 65,
    code: "MSP66053M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Principal White", "Principal Grey"],
    price: 50.99,
    inStock: true,
    image: null,
  },
  {
    id: 66,
    code: "MSP66054M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Leading Beige", "Leading Charcoal"],
    price: 51.99,
    inStock: true,
    image: null,
  },
  {
    id: 67,
    code: "MSP66055M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Chief White", "Chief Grey"],
    price: 52.99,
    inStock: true,
    image: null,
  },
  {
    id: 68,
    code: "MSP66056M",
    name: "Porcelain Tile",
    category: "600x600 Porcelain",
    sizes: ["600x600"],
    colors: ["Head Cream", "Head Brown"],
    price: 53.99,
    inStock: true,
    image: null,
  },

  // 60x120 Glazed
  {
    id: 69,
    code: "NRP61011",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["White", "Grey", "Beige", "Anthracite"],
    price: 65.99,
    inStock: true,
    image: null,
  },
  {
    id: 70,
    code: "NRP61012",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Marble Effect", "Concrete Grey"],
    price: 68.99,
    inStock: true,
    image: null,
  },
  {
    id: 71,
    code: "NRP61013",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Stone White", "Stone Grey"],
    price: 67.99,
    inStock: true,
    image: null,
  },
  {
    id: 72,
    code: "NRP61014",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Ceramic White", "Ceramic Grey"],
    price: 66.99,
    inStock: true,
    image: null,
  },
  {
    id: 73,
    code: "NRP61015",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Porcelain White", "Porcelain Grey"],
    price: 69.99,
    inStock: true,
    image: null,
  },
  {
    id: 74,
    code: "NRP61016",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Glazed Beige", "Glazed Brown"],
    price: 68.99,
    inStock: true,
    image: null,
  },
  {
    id: 75,
    code: "NRP61005",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Finish White", "Finish Grey"],
    price: 67.99,
    inStock: true,
    image: null,
  },
  {
    id: 76,
    code: "NRP61006",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Surface Beige", "Surface Grey"],
    price: 66.99,
    inStock: true,
    image: null,
  },
  {
    id: 77,
    code: "NRP61009",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Coat White", "Coat Grey"],
    price: 68.99,
    inStock: true,
    image: null,
  },
  {
    id: 78,
    code: "NRP61010",
    name: "Large Format Glazed Tile",
    category: "60x120 Glazed",
    sizes: ["60x120"],
    colors: ["Layer Cream", "Layer Brown"],
    price: 67.99,
    inStock: true,
    image: null,
  },

  // 60x120 Polished
  {
    id: 79,
    code: "NRP61003",
    name: "Large Format Polished Tile",
    category: "60x120 Polished",
    sizes: ["60x120"],
    colors: ["Marble White", "Marble Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 80,
    code: "NRP61004",
    name: "Large Format Polished Tile",
    category: "60x120 Polished",
    sizes: ["60x120"],
    colors: ["Ivory Polish", "Pearl Grey"],
    price: 74.99,
    inStock: true,
    image: null,
  },
  {
    id: 81,
    code: "NRP61007",
    name: "Large Format Polished Tile",
    category: "60x120 Polished",
    sizes: ["60x120"],
    colors: ["Shine White", "Shine Grey"],
    price: 73.99,
    inStock: true,
    image: null,
  },
  {
    id: 82,
    code: "NRP61008",
    name: "Large Format Polished Tile",
    category: "60x120 Polished",
    sizes: ["60x120"],
    colors: ["Gloss Beige", "Gloss Brown"],
    price: 75.99,
    inStock: true,
    image: null,
  },

  // 60x120 MSP Series
  {
    id: 83,
    code: "MSP61002AM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Series A White", "Series A Grey"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 84,
    code: "MSP61002BM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Series B Beige", "Series B Brown"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 85,
    code: "MSP61002CM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Series C White", "Series C Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 86,
    code: "MSP61002DM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Series D Cream", "Series D Charcoal"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 87,
    code: "MSP61003AM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Line A White", "Line A Grey"],
    price: 73.99,
    inStock: true,
    image: null,
  },
  {
    id: 88,
    code: "MSP61003BM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Line B Beige", "Line B Brown"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 89,
    code: "MSP61003CM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Line C White", "Line C Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 90,
    code: "MSP61003DM",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Line D Cream", "Line D Black"],
    price: 74.99,
    inStock: true,
    image: null,
  },
  {
    id: 91,
    code: "MSP61006M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Type 6 White", "Type 6 Grey"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 92,
    code: "MSP61007M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Type 7 Beige", "Type 7 Brown"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 93,
    code: "MSP61008M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Type 8 White", "Type 8 Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 94,
    code: "MSP61009M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Type 9 Cream", "Type 9 Charcoal"],
    price: 73.99,
    inStock: true,
    image: null,
  },
  {
    id: 95,
    code: "MSP61010M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 10 White", "Model 10 Grey"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 96,
    code: "MSP61011M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 11 Beige", "Model 11 Brown"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 97,
    code: "MSP61012M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 12 White", "Model 12 Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 98,
    code: "MSP61013M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 13 Cream", "Model 13 Black"],
    price: 74.99,
    inStock: true,
    image: null,
  },
  {
    id: 99,
    code: "MSP61014M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 14 White", "Model 14 Grey"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 100,
    code: "MSP61015M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 15 Beige", "Model 15 Charcoal"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 101,
    code: "MSP61016M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 16 White", "Model 16 Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 102,
    code: "MSP61017M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 17 Cream", "Model 17 Brown"],
    price: 73.99,
    inStock: true,
    image: null,
  },
  {
    id: 103,
    code: "MSP61018M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 18 White", "Model 18 Grey"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 104,
    code: "MSP61019M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 19 Beige", "Model 19 Black"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 105,
    code: "MSP61020M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 20 White", "Model 20 Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 106,
    code: "MSP61021M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 21 Cream", "Model 21 Charcoal"],
    price: 74.99,
    inStock: true,
    image: null,
  },
  {
    id: 107,
    code: "MSP61022M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 22 White", "Model 22 Grey"],
    price: 70.99,
    inStock: true,
    image: null,
  },
  {
    id: 108,
    code: "MSP61023M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 23 Beige", "Model 23 Brown"],
    price: 71.99,
    inStock: true,
    image: null,
  },
  {
    id: 109,
    code: "MSP61024M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 24 White", "Model 24 Grey"],
    price: 72.99,
    inStock: true,
    image: null,
  },
  {
    id: 110,
    code: "MSP61025M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 25 Cream", "Model 25 Black"],
    price: 73.99,
    inStock: true,
    image: null,
  },
  {
    id: 111,
    code: "MSP61026M",
    name: "Large Format Porcelain",
    category: "60x120 Porcelain",
    sizes: ["60x120"],
    colors: ["Model 26 White", "Model 26 Grey"],
    price: 74.99,
    inStock: true,
    image: null,
  },
];

export const ProductProvider = ({ children }) => {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);

  // Load from localStorage or use defaults
  useEffect(() => {
    const stored = localStorage.getItem("ncc_products");
    if (stored) {
      setProducts(JSON.parse(stored));
    } else {
      setProducts(defaultProducts);
      localStorage.setItem("ncc_products", JSON.stringify(defaultProducts));
    }
    setLoading(false);
  }, []);

  // Save to localStorage whenever products change
  useEffect(() => {
    if (!loading) {
      localStorage.setItem("ncc_products", JSON.stringify(products));
    }
  }, [products, loading]);

  // 🔧 Admin: Add new product
  const addProduct = (product) => {
    const newProduct = {
      ...product,
      id: Date.now(),
      inStock: product.inStock !== undefined ? product.inStock : true,
      createdAt: new Date().toISOString(),
    };
    setProducts([newProduct, ...products]);
    return newProduct;
  };

  // 🔧 Admin: Update product
  const updateProduct = (productId, updates) => {
    setProducts(
      products.map((p) =>
        p.id === productId
          ? { ...p, ...updates, updatedAt: new Date().toISOString() }
          : p,
      ),
    );
  };

  // 🔧 Admin: Delete product
  const deleteProduct = (productId) => {
    if (window.confirm("Are you sure you want to delete this product?")) {
      setProducts(products.filter((p) => p.id !== productId));
    }
  };

  // 🔧 Admin: Toggle stock status
  const toggleStock = (productId) => {
    setProducts(
      products.map((p) =>
        p.id === productId ? { ...p, inStock: !p.inStock } : p,
      ),
    );
  };

  // 🔧 Admin: Update product image
  const updateProductImage = (productId, imageData) => {
    setProducts(
      products.map((p) =>
        p.id === productId ? { ...p, image: imageData } : p,
      ),
    );
  };

  // Filter helpers
  const getByCategory = (category) =>
    products.filter((p) => p.category === category);

  const getInStock = () => products.filter((p) => p.inStock);

  const getById = (id) => products.find((p) => p.id === Number(id));

  const categories = [...new Set(products.map((p) => p.category))].sort();

  // Search functionality
  const searchProducts = (query) => {
    const q = query.toLowerCase();
    return products.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.code.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q),
    );
  };

  return (
    <ProductContext.Provider
      value={{
        products,
        categories,
        loading,
        addProduct,
        updateProduct,
        deleteProduct,
        toggleStock,
        updateProductImage,
        getByCategory,
        getInStock,
        getById,
        searchProducts,
        totalProducts: products.length,
        inStockCount: products.filter((p) => p.inStock).length,
        outOfStockCount: products.filter((p) => !p.inStock).length,
      }}
    >
      {children}
    </ProductContext.Provider>
  );
};
